### ISSUE TITLE
make tun device automatic and/or configurable

### ISSUE THREAD

**Issue by swills** [freebsd-net/packetdrill#10]
Right now, packetdrill hard codes the tun device name, which is inconvenient if you are using tun0 for a vpn. Would be nice to have packetdrill find one automatically and/or make it configurable via command line or config file.

**Comment by tuexen** [comment]
I think you are mostly interested in FreeBSD, right? I can simply add an automatic choice if the sysctl variable `net.link.tun.devfs_cloning` is non-zero. Would that be sufficient?

**Comment by swills** [comment]
Yeah, I think that would work, thanks!

**Comment by tuexen** [comment]
I merged some code such that now the next free `tun` interface is used automatically on *BSD. This was already the case for Linux. After a test terminates, the `tun` interface is destroyed on *BSD, as it is already on Linux. This provides a consistent behaviour on all platforms.

I added also the `--tun_dev` command line option to specify a `tun` interface to be used and the `--persistent_tun_dev` command line option to keep the `tun` interface specified by the `--tun_dev` command line option around. This means you need to specify `--tun_dev=tun0 --persistent_tun_dev` to get back the old behaviour.

I hope this addresses your issue. Let me know if you have any questions or find any issues.
